// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSharingApplication.WebServices.Rest.Photos.Infrastructure.Data;

#nullable disable

namespace PhotoSharingApplication.WebServices.Rest.Photos.Migrations
{
    [DbContext(typeof(PhotosDbContext))]
    [Migration("20220211104314_LatLon")]
    partial class LatLon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("PhotoSharingApplication.Shared.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("PhotoSharingApplication.Shared.Entities.PhotoImage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PhotoFile")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("PhotoSharingApplication.Shared.Entities.PhotoImage", b =>
                {
                    b.HasOne("PhotoSharingApplication.Shared.Entities.Photo", null)
                        .WithOne("PhotoImage")
                        .HasForeignKey("PhotoSharingApplication.Shared.Entities.PhotoImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoSharingApplication.Shared.Entities.Photo", b =>
                {
                    b.Navigation("PhotoImage");
                });
#pragma warning restore 612, 618
        }
    }
}
