version: '3.4'

services:
  photosharingapplication.identityserver:
    image: ${DOCKER_REGISTRY-}photosharingapplicationidentityserver
    build:
      context: .
      dockerfile: PhotoSharingApplication.IdentityServer/Dockerfile

  photosharingapplication.webservices.rest.photos:
    image: ${DOCKER_REGISTRY-}photosharingapplicationwebservicesrestphotos
    build:
      context: .
      dockerfile: PhotoSharingApplication.WebServices.REST.Photos/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=PhotoSharingApplicationContextBlazorLabs;User Id=sa;Password=Pass@word
    depends_on:
      - sqldata

  photosharingapplication.webservices.grpc.comments:
    image: ${DOCKER_REGISTRY-}photosharingapplicationwebservicesgrpccomments
    build:
      context: .
      dockerfile: PhotoSharingApplication.WebServices.Grpc.Comments/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=PhotoSharingApplicationContextBlazorLabs;User Id=sa;Password=Pass@word
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  photosharingapplication.frontend.blazorwebassembly:
    image: ${DOCKER_REGISTRY-}photosharingapplicationfrontendblazorwebassembly
    build:
      context: .
      dockerfile: PhotoSharingApplication.Frontend.BlazorWebAssembly/Dockerfile
    depends_on:
      - photosharingapplication.identityserver
      - photosharingapplication.webservices.rest.photos
      - photosharingapplication.webservices.grpc.comments